version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=chaqui
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=josue.chaqui@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=test123
    ports:
      - 5050:80
